apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: website
spec:
  maxReplicas: 10 
  minReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: website
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50