apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: website
spec:
  maxReplicas: 1000 
  minReplicas: 500
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: website
  targetCPUUtilizationPercentage: 90